/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbutils;

import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import conexoes.clBuscaResultSet;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Valdir Cordeiro
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

        /*
         try {
         Properties props = new Properties();
         props.put("logoString", "PragmaSUM");
         AluminiumLookAndFeel.setCurrentTheme(props);
         UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
         SwingUtilities.updateComponentTreeUI(this);
         } catch (Exception e) {
         // TODO: handle exception
         }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SQLGenerico = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        tabelaEntrada = new javax.swing.JTextField();
        ImportarGenerico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ColunaEntrada = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        comboConexão = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bd = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        porta = new javax.swing.JTextField();
        host = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        bd5 = new javax.swing.JTextField();
        senha5 = new javax.swing.JTextField();
        user5 = new javax.swing.JTextField();
        porta5 = new javax.swing.JTextField();
        host5 = new javax.swing.JTextField();
        status5 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        host1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        porta1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        user1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        senha1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bd1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        status1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoDirAdpm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        host2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        user2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        senha2 = new javax.swing.JTextField();
        bd2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        porta2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        status2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        host3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        porta3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        user3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        senha3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        bd3 = new javax.swing.JTextField();
        status3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        host4 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        porta4 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        user4 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        senha4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        bd4 = new javax.swing.JTextField();
        status4 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        campoDirParadox = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(null);

        jScrollPane2.setToolTipText("");

        SQLGenerico.setColumns(20);
        SQLGenerico.setRows(5);
        jScrollPane2.setViewportView(SQLGenerico);

        jLabel49.setText("Nome da Tabela de Entrada:");

        tabelaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaEntradaActionPerformed(evt);
            }
        });

        ImportarGenerico.setText("Importar");
        ImportarGenerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarGenericoActionPerformed(evt);
            }
        });

        jLabel6.setText("Consulta SQL:");

        jLabel9.setText("Colunas de Entrada:");

        ColunaEntrada.setColumns(20);
        ColunaEntrada.setRows(5);
        jScrollPane3.setViewportView(ColunaEntrada);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Coloque como apelido na consulta SQL o nome das colunas de entrada.");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboConexão.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a conexão configurada", "SDBF --> POSTGRESQL", "MSSQLSERVER --> POSTGRESQL", "MySQL --> POSTGRESQL" }));

        jLabel37.setText("Conexão Configurada:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("Separe as colunas por virgula e sem espaços.");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel30Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel30Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboConexão, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                                .addComponent(ImportarGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tabelaEntrada)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboConexão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImportarGenerico, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel4.add(jPanel30);
        jPanel30.setBounds(0, 0, 920, 520);

        jTabbedPane2.addTab("Importação/Conversão", jPanel4);

        jPanel6.setLayout(null);

        jPanel9.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ip/Host:");
        jPanel9.add(jLabel1);
        jLabel1.setBounds(10, 10, 70, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Porta:");
        jPanel9.add(jLabel2);
        jLabel2.setBounds(20, 40, 60, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User:");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(10, 70, 70, 20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Senha:");
        jPanel9.add(jLabel5);
        jLabel5.setBounds(10, 100, 70, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nome BD:");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(10, 130, 70, 20);

        bd.setText("tSaoSebastiaoMaranhao09");
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });
        jPanel9.add(bd);
        bd.setBounds(90, 130, 240, 20);

        senha.setText("427623");
        jPanel9.add(senha);
        senha.setBounds(90, 100, 70, 20);

        user.setText("root");
        jPanel9.add(user);
        user.setBounds(90, 70, 70, 20);

        porta.setText("3306");
        jPanel9.add(porta);
        porta.setBounds(90, 40, 50, 20);

        host.setText("localhost");
        jPanel9.add(host);
        host.setBounds(90, 10, 96, 20);

        status.setForeground(new java.awt.Color(0, 126, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("Espera");
        status.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        status.setBorder(javax.swing.BorderFactory.createTitledBorder(" Status "));
        jPanel9.add(status);
        status.setBounds(480, 30, 120, 90);

        jButton3.setText("<html><center>Inicializar Conexão");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);
        jButton3.setBounds(490, 50, 100, 50);

        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Recebe Dados");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(480, 120, 120, 20);

        jTabbedPane4.addTab("E-Mysql", jPanel9);

        jPanel24.setLayout(null);

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("Ip/Host:");
        jPanel24.add(jLabel42);
        jLabel42.setBounds(10, 10, 70, 20);

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("Porta:");
        jPanel24.add(jLabel43);
        jLabel43.setBounds(20, 40, 60, 20);

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("User:");
        jPanel24.add(jLabel44);
        jLabel44.setBounds(10, 70, 70, 20);

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setText("Senha:");
        jPanel24.add(jLabel45);
        jLabel45.setBounds(10, 100, 70, 20);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("Nome BD:");
        jPanel24.add(jLabel46);
        jLabel46.setBounds(10, 130, 70, 20);

        bd5.setText("BKPBancos");
        jPanel24.add(bd5);
        bd5.setBounds(90, 130, 240, 20);

        senha5.setText("325082");
        senha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha5ActionPerformed(evt);
            }
        });
        jPanel24.add(senha5);
        senha5.setBounds(90, 100, 70, 20);

        user5.setText("postgres");
        jPanel24.add(user5);
        user5.setBounds(90, 70, 70, 20);

        porta5.setText("5432");
        jPanel24.add(porta5);
        porta5.setBounds(90, 40, 50, 20);

        host5.setText("localhost");
        jPanel24.add(host5);
        host5.setBounds(90, 10, 96, 20);

        status5.setForeground(new java.awt.Color(0, 126, 255));
        status5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status5.setText("Espera");
        status5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        status5.setBorder(javax.swing.BorderFactory.createTitledBorder(" Status "));
        jPanel24.add(status5);
        status5.setBounds(480, 30, 120, 90);

        jButton24.setText("<html><center>Inicializar Conexão");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton24);
        jButton24.setBounds(490, 50, 100, 50);

        jLabel47.setForeground(new java.awt.Color(0, 102, 102));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Recebe Dados");
        jPanel24.add(jLabel47);
        jLabel47.setBounds(480, 120, 120, 20);

        jTabbedPane4.addTab("E-Postgres", jPanel24);

        jPanel10.setLayout(null);

        host1.setText("localhost");
        jPanel10.add(host1);
        host1.setBounds(90, 10, 96, 20);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Ip/Host:");
        jPanel10.add(jLabel11);
        jLabel11.setBounds(10, 10, 70, 20);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Porta:");
        jPanel10.add(jLabel12);
        jLabel12.setBounds(20, 40, 60, 20);

        porta1.setText("3306");
        jPanel10.add(porta1);
        porta1.setBounds(90, 40, 50, 20);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("User:");
        jPanel10.add(jLabel13);
        jLabel13.setBounds(10, 70, 70, 20);

        user1.setText("root");
        jPanel10.add(user1);
        user1.setBounds(90, 70, 70, 20);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Senha:");
        jPanel10.add(jLabel14);
        jLabel14.setBounds(10, 100, 70, 20);

        senha1.setText("427623");
        jPanel10.add(senha1);
        senha1.setBounds(90, 100, 70, 20);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Nome BD:");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(10, 130, 70, 20);

        bd1.setText("TJOAQUIM2007");
        jPanel10.add(bd1);
        bd1.setBounds(90, 130, 240, 20);

        jButton4.setText("<html><center>Inicializar Conexão");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4);
        jButton4.setBounds(490, 50, 100, 50);

        status1.setForeground(new java.awt.Color(0, 126, 255));
        status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status1.setText("Espera");
        status1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        status1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Status "));
        jPanel10.add(status1);
        status1.setBounds(480, 30, 120, 90);

        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Extrai Dados");
        jPanel10.add(jLabel16);
        jLabel16.setBounds(480, 120, 120, 20);

        jTabbedPane4.addTab("S-Mysql", jPanel10);

        jPanel11.setLayout(null);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Diretório:");
        jPanel11.add(jLabel7);
        jLabel7.setBounds(10, 20, 60, 20);

        campoDirAdpm.setText("D:\\Projetos HLH\\Outros\\IBIAI2014\\IBIAI2014");
        jPanel11.add(campoDirAdpm);
        campoDirAdpm.setBounds(80, 20, 370, 20);

        jButton1.setText("...");
        jButton1.setToolTipText("Procurar Diretório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1);
        jButton1.setBounds(460, 20, 30, 20);

        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Extrai Dados");
        jPanel11.add(jLabel18);
        jLabel18.setBounds(380, 90, 120, 20);

        jButton16.setText("Set Conexão DBF Padrao");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton16);
        jButton16.setBounds(320, 60, 180, 23);

        jTabbedPane4.addTab("S-Dbf", jPanel11);

        jPanel12.setLayout(null);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Ip/Host:");
        jPanel12.add(jLabel19);
        jLabel19.setBounds(10, 10, 70, 20);

        host2.setText("localhost");
        jPanel12.add(host2);
        host2.setBounds(90, 10, 96, 20);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("User:");
        jPanel12.add(jLabel20);
        jLabel20.setBounds(10, 70, 70, 20);

        user2.setText("postgres");
        jPanel12.add(user2);
        user2.setBounds(90, 70, 70, 20);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Senha:");
        jPanel12.add(jLabel21);
        jLabel21.setBounds(10, 100, 70, 20);

        senha2.setText("427623");
        jPanel12.add(senha2);
        senha2.setBounds(90, 100, 70, 20);

        bd2.setText("ver");
        jPanel12.add(bd2);
        bd2.setBounds(90, 130, 240, 20);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Nome BD:");
        jPanel12.add(jLabel22);
        jLabel22.setBounds(10, 130, 70, 20);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Porta:");
        jPanel12.add(jLabel23);
        jLabel23.setBounds(20, 40, 60, 20);

        porta2.setText("5432");
        jPanel12.add(porta2);
        porta2.setBounds(90, 40, 50, 20);

        jButton8.setText("<html><center>Inicializar Conexão");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton8);
        jButton8.setBounds(470, 50, 100, 50);

        status2.setForeground(new java.awt.Color(0, 126, 255));
        status2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status2.setText("Espera");
        status2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        status2.setBorder(javax.swing.BorderFactory.createTitledBorder(" Status "));
        jPanel12.add(status2);
        status2.setBounds(460, 30, 120, 90);

        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Extrai Dados");
        jPanel12.add(jLabel24);
        jLabel24.setBounds(460, 120, 120, 20);

        jTabbedPane4.addTab("S-Postgres", jPanel12);

        jPanel7.setLayout(null);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Ip/Host:");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(10, 10, 70, 20);

        host3.setText("localhost");
        jPanel7.add(host3);
        host3.setBounds(90, 10, 96, 20);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Porta:");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(20, 40, 60, 20);

        porta3.setText("1433");
        jPanel7.add(porta3);
        porta3.setBounds(90, 40, 50, 20);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("User:");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(10, 70, 70, 20);

        user3.setText("sa");
        jPanel7.add(user3);
        user3.setBounds(90, 70, 70, 20);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Senha:");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(10, 100, 70, 20);

        senha3.setText("sa");
        jPanel7.add(senha3);
        senha3.setBounds(90, 100, 70, 20);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Nome BD:");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(10, 130, 70, 20);

        bd3.setText("DBFLH");
        jPanel7.add(bd3);
        bd3.setBounds(90, 130, 240, 20);

        status3.setForeground(new java.awt.Color(0, 126, 255));
        status3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status3.setText("Espera");
        status3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        status3.setBorder(javax.swing.BorderFactory.createTitledBorder(" Status "));
        jPanel7.add(status3);
        status3.setBounds(460, 30, 120, 90);

        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Extrai Dados");
        jPanel7.add(jLabel30);
        jLabel30.setBounds(460, 120, 120, 20);

        jButton10.setText("<html><center>Inicializar Conexão");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10);
        jButton10.setBounds(470, 50, 100, 50);

        jTabbedPane4.addTab("S-SqlServer", jPanel7);

        jPanel17.setLayout(null);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Ip/Host:");
        jPanel17.add(jLabel31);
        jLabel31.setBounds(10, 10, 70, 20);

        host4.setText("localhost");
        jPanel17.add(host4);
        host4.setBounds(90, 10, 96, 20);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Porta:");
        jPanel17.add(jLabel32);
        jLabel32.setBounds(20, 40, 60, 20);

        porta4.setText("3050");
        jPanel17.add(porta4);
        porta4.setBounds(90, 40, 50, 20);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("User:");
        jPanel17.add(jLabel33);
        jLabel33.setBounds(10, 70, 70, 20);

        user4.setText("sysdba");
        jPanel17.add(user4);
        user4.setBounds(90, 70, 70, 20);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Senha:");
        jPanel17.add(jLabel34);
        jLabel34.setBounds(10, 100, 70, 20);

        senha4.setText("masterkey");
        jPanel17.add(senha4);
        senha4.setBounds(90, 100, 70, 20);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("End. BD:");
        jPanel17.add(jLabel35);
        jLabel35.setBounds(10, 130, 70, 20);

        bd4.setText("C:\\Documents and Settings\\adm\\Desktop\\RHEXERCICIOCampo\\RHEXERCICIO.GDB");
        jPanel17.add(bd4);
        bd4.setBounds(90, 130, 450, 20);

        status4.setForeground(new java.awt.Color(0, 126, 255));
        status4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status4.setText("Espera");
        status4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        status4.setBorder(javax.swing.BorderFactory.createTitledBorder(" Status "));
        jPanel17.add(status4);
        status4.setBounds(590, 10, 140, 90);

        jLabel36.setForeground(new java.awt.Color(0, 102, 102));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Extrai Dados");
        jPanel17.add(jLabel36);
        jLabel36.setBounds(590, 100, 140, 20);

        jButton12.setText("<html><center>Inicializar Conexão");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton12);
        jButton12.setBounds(610, 30, 100, 50);

        jButton13.setText("...");
        jButton13.setToolTipText("Procurar Diretório");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton13);
        jButton13.setBounds(550, 130, 40, 20);

        jTabbedPane4.addTab("S-Interbase", jPanel17);

        jPanel22.setLayout(null);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Diretório:");
        jPanel22.add(jLabel40);
        jLabel40.setBounds(10, 10, 60, 20);

        campoDirParadox.setText("C:\\Compartilhamento\\D0837022013_21102013_1643\\trib\\guias\\226\\2013");
        jPanel22.add(campoDirParadox);
        campoDirParadox.setBounds(80, 10, 400, 20);

        jButton22.setText("...");
        jButton22.setToolTipText("Procurar Diretório");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton22);
        jButton22.setBounds(490, 10, 30, 20);

        jLabel41.setForeground(new java.awt.Color(0, 102, 102));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Extrai Dados");
        jPanel22.add(jLabel41);
        jLabel41.setBounds(400, 80, 120, 20);

        jButton23.setText("Set Conexão Paradox Padrao");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton23);
        jButton23.setBounds(330, 50, 190, 23);

        jTabbedPane4.addTab("S-Paradox", jPanel22);

        jPanel6.add(jTabbedPane4);
        jTabbedPane4.setBounds(0, 0, 920, 530);

        jTabbedPane2.addTab("Conexões (S= saída | E= entrada)", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        getConexaoParadoxPadrao();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        JFileChooser chose = new JFileChooser(campoDirParadox.getText());
        chose.setDialogTitle("Selecione o diretório da Base de Dados, Ex: C:\\BANCODEDADOS");
        chose.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chose.showSaveDialog(this) == 0) {
            campoDirParadox.setText(chose.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        JFileChooser chose = new JFileChooser(bd4.getText());
        chose.setDialogTitle("Selecione o arquivo de Banco de Dados, Ex: C:\\BANCODEDADOS\\arquivo1.GDB");
        chose.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (chose.showSaveDialog(this) == 0) {
            bd4.setText(chose.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        getConexaoInterBase();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        getConexaoMSSQLSERVER();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        getConexaoPG();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        getConexaoDBFPadrao();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chose = new JFileChooser(campoDirAdpm.getText());
        chose.setDialogTitle("Selecione o diretório da Base de Dados, Ex: C:\\BANCODEDADOS");
        chose.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chose.showSaveDialog(this) == 0) {
            campoDirAdpm.setText(chose.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getConexaoSQL();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        getConexaoPostgresEntrada();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void senha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getConexaoMySqlEntrada();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaEntradaActionPerformed

    private void ImportarGenericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarGenericoActionPerformed
        // TODO add your handling code here:

        if (comboConexão.getSelectedItem() == "SDBF --> POSTGRESQL") {
            SDBFparaPostgreSQL();
        } else {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a conexão configurada por você na aba conexões! ");
        }

        //MSSQLSERVER-- > POSTGRESQL
        //MySQL-- > POSTGRESQL

    }//GEN-LAST:event_ImportarGenericoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ColunaEntrada;
    private javax.swing.JButton ImportarGenerico;
    private javax.swing.JTextArea SQLGenerico;
    private javax.swing.JTextField bd;
    private javax.swing.JTextField bd1;
    private javax.swing.JTextField bd2;
    private javax.swing.JTextField bd3;
    private javax.swing.JTextField bd4;
    private javax.swing.JTextField bd5;
    private javax.swing.JTextField campoDirAdpm;
    private javax.swing.JTextField campoDirParadox;
    private javax.swing.JComboBox comboConexão;
    private javax.swing.JTextField host;
    private javax.swing.JTextField host1;
    private javax.swing.JTextField host2;
    private javax.swing.JTextField host3;
    private javax.swing.JTextField host4;
    private javax.swing.JTextField host5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField porta;
    private javax.swing.JTextField porta1;
    private javax.swing.JTextField porta2;
    private javax.swing.JTextField porta3;
    private javax.swing.JTextField porta4;
    private javax.swing.JTextField porta5;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField senha1;
    private javax.swing.JTextField senha2;
    private javax.swing.JTextField senha3;
    private javax.swing.JTextField senha4;
    private javax.swing.JTextField senha5;
    private javax.swing.JLabel status;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel status3;
    private javax.swing.JLabel status4;
    private javax.swing.JLabel status5;
    private javax.swing.JTextField tabelaEntrada;
    private javax.swing.JTextField user;
    private javax.swing.JTextField user1;
    private javax.swing.JTextField user2;
    private javax.swing.JTextField user3;
    private javax.swing.JTextField user4;
    private javax.swing.JTextField user5;
    // End of variables declaration//GEN-END:variables
    private Statement stmtDBFSaida = null;
    private Statement stmtParadoxSaida = null;
    private Statement stmtParadoxSaida2 = null;
    private Statement stmtMySqlSaida = null;
    private Statement stmtPgSqlSaida = null;
    private Statement stmtPgEntrada = null;
    private Statement stmtPgEntrada2 = null;
    private Statement stmtSqlEntrada = null;
    private Statement stmtSqlEntrada2 = null;
    private Statement stmtSqlEntrada3 = null;
    private Statement stmtSqlEntrada4 = null;
    private Statement stmtMsSqlServerSaida = null;
    private Statement stmtMsSqlServerSaida2 = null;
    private Statement stmtInterBaseSaida = null;
    private int codEndPess = 0;
    private String sin = ">";

    /**
     * *
     * Funções de Conexão
     */
    private void getConexaoPostgresEntrada() {
        conexoes.Conectar.setDriveJDBC("org.postgresql.Driver");
        conexoes.Conectar.setIpServidor(host5.getText());
        conexoes.Conectar.setNomeDB(bd5.getText());
        conexoes.Conectar.setPorta(porta5.getText());
        conexoes.Conectar.setSenhaBanco(senha5.getText());
        conexoes.Conectar.setUsurioBanco(user5.getText());
        conexoes.Conectar.setUrlConexao("jdbc:postgresql://" + conexoes.Conectar.getIpServidor() + ":" + conexoes.Conectar.getPorta() + "/" + conexoes.Conectar.getNomeDB());
        //if(conexoes.Conectar.isInicializado() > 0){
        stmtPgEntrada = conexoes.Conectar.getStatement();
        stmtPgEntrada2 = conexoes.Conectar.getStatement();
        //stmtSqlEntrada3 = conexoes.Conectar.getStatement();
        //stmtSqlEntrada4 = conexoes.Conectar.getStatement();
        if (conexoes.clBuscaResultSet.getCount("SELECT DATNAME FROM PG_DATABASE where datname like '" + bd5.getText() + "' ORDER BY LOWER(DATNAME)  ") > 0) {
            status5.setForeground(new Color(0, 153, 51));
            status5.setText("Conectado");

        } else {
            status5.setForeground(new Color(204, 0, 0));
            status5.setText("Desconectado");

        }
    }

    private void getConexaoPG() {
        try {
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:postgresql://" + host2.getText().trim() + ":" + porta2.getText() + "/" + bd2.getText(), user2.getText(), senha2.getText());
            stmtPgSqlSaida = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs0 = stmtPgSqlSaida.executeQuery("SELECT DATNAME FROM PG_DATABASE");
            if (rs0.next()) {
                System.out.println(rs0.getString(1));
            }
            int quantBancos = 0;
            ResultSet rs = stmtPgSqlSaida.executeQuery("select relname from pg_stat_user_tables order by relname ");
            if (rs.next()) {
                System.out.println(rs.getString(1));
                quantBancos = 1;
            } else {
                quantBancos = 0;
            }
            if (quantBancos > 0) {
                status2.setForeground(new Color(0, 153, 51));
                status2.setText("Conectado");
                //processar.setEnabled(true);
            } else {
                status2.setForeground(new Color(204, 0, 0));
                status2.setText("Desconectado");
                //processar.setEnabled(false);
            }
            while (rs.next()) {
                ;//cDir.addItem((Object)rs.getString("DATNAME"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getConexaoMySqlEntrada() {
        conexoes.Conectar.setDriveJDBC("com.mysql.jdbc.Driver");
        conexoes.Conectar.setIpServidor(host.getText());
        conexoes.Conectar.setNomeDB(bd.getText());
        conexoes.Conectar.setPorta(porta.getText());
        conexoes.Conectar.setSenhaBanco(senha.getText());
        conexoes.Conectar.setUsurioBanco(user.getText());
        conexoes.Conectar.setUrlConexao("jdbc:mysql://" + conexoes.Conectar.getIpServidor() + ":" + conexoes.Conectar.getPorta() + "/" + conexoes.Conectar.getNomeDB());
        //if(conexoes.Conectar.isInicializado() > 0){
        stmtSqlEntrada = conexoes.Conectar.getStatement();
        stmtSqlEntrada2 = conexoes.Conectar.getStatement();
        stmtSqlEntrada3 = conexoes.Conectar.getStatement();
        stmtSqlEntrada4 = conexoes.Conectar.getStatement();
        if (conexoes.clBuscaResultSet.getCount("SHOW TABLES FROM " + bd.getText()) > 0) {
            status.setForeground(new Color(0, 153, 51));
            status.setText("Conectado");
        } else {
            status.setForeground(new Color(204, 0, 0));
            status.setText("Desconectado");
        }
    }

    private void getConexaoMSSQLSERVER() {//Saida
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlserver://" + host3.getText() + ":" + porta3.getText() + ";databasename=" + bd3.getText(), user3.getText(), senha3.getText());
            stmtMsSqlServerSaida = conn.createStatement(java.sql.ResultSet.TYPE_SCROLL_SENSITIVE, java.sql.ResultSet.CONCUR_UPDATABLE);
            stmtMsSqlServerSaida2 = conn.createStatement(java.sql.ResultSet.TYPE_SCROLL_SENSITIVE, java.sql.ResultSet.CONCUR_UPDATABLE);

            int quantBancos = 0;
            ResultSet rs = stmtMsSqlServerSaida.executeQuery("SELECT     '' AS Expr1");
            if (rs.next()) {
                quantBancos = 1;
            } else {
                quantBancos = 0;
            }
            if (quantBancos > 0) {
                status3.setForeground(new Color(0, 153, 51));
                status3.setText("Conectado");
                //processar.setEnabled(true);
            } else {
                status3.setForeground(new Color(204, 0, 0));
                status3.setText("Desconectado");
                //processar.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
            status3.setForeground(new Color(204, 0, 0));
            status3.setText("Desconectado");
        }
    }

    private void getConexaoInterBase() {//Saida
        try {
            Class.forName("interbase.interclient.Driver");
            //jdbc:interbase://localhost/C:\Documents and Settings\adm\Desktop\RHEXERCICIOCampo\RHEXERCICIO.GDB
            Connection conn = java.sql.DriverManager.getConnection("jdbc:interbase://" + host4.getText() + ":" + porta4.getText() + "/" + bd4.getText(), user4.getText(), senha4.getText());
            stmtInterBaseSaida = conn.createStatement(java.sql.ResultSet.TYPE_SCROLL_SENSITIVE, java.sql.ResultSet.CONCUR_UPDATABLE);

            int quantBancos = 0;
            ResultSet rs = stmtInterBaseSaida.executeQuery("show databases");
            if (rs.next()) {
                quantBancos = 1;
            } else {
                quantBancos = 0;
            }
            if (quantBancos > 0) {
                status4.setForeground(new Color(0, 153, 51));
                status4.setText("Conectado");
                //processar.setEnabled(true);
            } else {
                status4.setForeground(new Color(204, 0, 0));
                status4.setText("Desconectado");
                //processar.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
            status4.setForeground(new Color(204, 0, 0));
            status4.setText("Desconectado");
        }
    }

    private void getConexaoSQL() {//Saida
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://" + host1.getText() + ":" + porta1.getText() + "/" + bd1.getText(), "root", "427623");
            stmtMySqlSaida = conn.createStatement(java.sql.ResultSet.TYPE_SCROLL_SENSITIVE, java.sql.ResultSet.CONCUR_UPDATABLE);

            int quantBancos = 0;
            ResultSet rs = stmtMySqlSaida.executeQuery("SHOW TABLES FROM " + bd1.getText());
            if (rs.next()) {
                quantBancos = 1;
            } else {
                quantBancos = 0;
            }
            if (quantBancos > 0) {
                status1.setForeground(new Color(0, 153, 51));
                status1.setText("Conectado");
                //processar.setEnabled(true);
            } else {
                status1.setForeground(new Color(204, 0, 0));
                status1.setText("Desconectado");
                //processar.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getConexaoParadoxPadrao() {
        try {
            String dirDBF = campoDirParadox.getText();
            Class.forName("com.hxtt.sql.paradox.ParadoxDriver");
            String sss = "jdbc:paradox:/" + dirDBF;
            System.out.println("url: " + sss);
            Connection conn = DriverManager.getConnection(sss);
            Connection conn2 = DriverManager.getConnection(sss);
            stmtParadoxSaida = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stmtParadoxSaida2 = conn2.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getConexaoDBFPadrao() {
        try {
            String dirDBF = campoDirAdpm.getText();
            Class.forName("com.hxtt.sql.dbf.DBFDriver");
            Connection conn = DriverManager.getConnection("jdbc:dbf:/" + dirDBF);
            stmtDBFSaida = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * *
     * Funções de Importação de dados
     */
    private void SDBFparaPostgreSQL() {

        if (campoDirAdpm.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Escolha o Diretório do banco de dados DBF antes de Processar.");
        } else {
            try {
                String dirDBF = campoDirAdpm.getText();
                Class.forName("com.hxtt.sql.dbf.DBFDriver");
                Connection conn = DriverManager.getConnection("jdbc:dbf:/" + dirDBF);
                stmtDBFSaida = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

                try {
                    ResultSet rs = stmtDBFSaida.executeQuery(SQLGenerico.getText());
                    if (rs.next()) {
                        clBuscaResultSet.setExecute("DELETE FROM " + tabelaEntrada.getText());
                        rs.beforeFirst();
                        ResultSet sr = clBuscaResultSet.getPesquisa("SELECT * FROM " + tabelaEntrada.getText());

                        String colunasSaida[];
                        String colunasEntrada[];

                        colunasEntrada = ColunaEntrada.getText().split(",");

                        while (rs.next()) {
                            sr.moveToInsertRow();

                            for (String colunasEntrada1 : colunasEntrada) {
                                sr.updateString(colunasEntrada1, "" + rs.getString(colunasEntrada1));
                                //escolheTipoVariavel(colunasEntrada[i], colunasSaida[i], sr, rs);
                            }

                            sr.insertRow();
                        }
                        rs.close();
                        JOptionPane.showMessageDialog(this, "Importação de dados concluída com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Cadastro de Servidores\nNão foi encontrado registro para importação.");
                    }
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(this, "Erro 1:\n" + e);
                }

            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Erro:\n" + e);
            }
        }

    }

    /**
     * *
     * Função para escolher qual o tipo de entrada do banco de dados.
     *
     * @param entrada
     * @param saida
     * @param sr
     * @param rs
     */
    private void escolheTipoVariavel(String entrada, String saida, ResultSet sr, ResultSet rs) {

        String entradas[] = entrada.split(" ");
        String saidas[] = saida.split(" ");

        System.out.println("" + entradas[0] + "|" + entradas[1] + "|" + saidas[0] + "|" + saidas[1]);

        try {
            if (saidas[0].equalsIgnoreCase("int")) {
                sr.updateInt(entradas[1].toString(), rs.getInt(saidas[1]));
            } else if (saidas[0].equalsIgnoreCase("char")) {
                sr.updateString(entradas[1], rs.getString(saidas[1]));
            } else if (saidas[0].equalsIgnoreCase("date")) {
                sr.updateDate(entradas[1], rs.getDate(saidas[1]));
            } else {
                JOptionPane.showMessageDialog(this, "Escolha um tipo compatível:");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro 1:\n" + e);
            e.printStackTrace();
        }

    }

}
